openapi: "3.0.1"
info:
  version: "1"
  title: "Helloworld documentation"


paths:

  /helloworld:
    post:
      summary: "Create a Helloworld translation"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Helloworld"
      security:
        - cognito: []
      responses:
        201:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Helloworld"

      x-amazon-apigateway-request-validator: validate_request
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 201
        uri: "${helloworld_arn}"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

components:
  schemas:
    Helloworld:
      type: object
      properties:
        language:
          type: string
        value:
          type: string


  securitySchemes:
    cognito:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
        - ${userpool_arn}

x-amazon-apigateway-request-validators:
  validate_request:
    validateRequestBody: true
    validateRequestParameters: true